### ISSUE TITLE
getting blank frames in results

### ISSUE THREAD

**Issue by Suvi-dha** [xuboming8/DSTNet#10]
Hi, I am inferencing on my own dataset and followed the directory structure of the dataset. My frames are of size 1920 by 1080 which I resized to 2048 by 1024 as suggested (in the multiples of 256). I also don't have the ground truth so in the yml file I kept both the low quality and ground truth data path as same. The code then successfully ran but I am getting blank black frames as output. Here's my data config and results. 

```
datasets:
  test_1:  # the 1st test dataset
    name: GOPRO
    type: VideoRecurrentSplitClipsTestDataset
    dataroot_gt: /home/suvidha/Diffusion/ResShift/testdata/blinkit_frames/RetinexFormer_NTIRE/NTIRE/blur
    dataroot_lq: /home/suvidha/Diffusion/ResShift/testdata/blinkit_frames/RetinexFormer_NTIRE/NTIRE/blur
    cache_data: True
    io_backend:
      type: disk

    num_frame: 10
    num_overlap: 0
```

![000000](https://github.com/xuboming8/DSTNet/assets/37800843/2519f97b-09c7-4704-b1a4-fb719707c868)
